"""empty message

Revision ID: 333e134afcf6
Revises: 
Create Date: 2022-05-02 17:52:53.168996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333e134afcf6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(length=100), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('date', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quizz')
    # ### end Alembic commands ###
